name: test-ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test-ruby:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby: ["2.5", "2.6", "2.7", "3.0"]
        include:
          - os: macos-latest
            ruby: "3.0"

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/prepare

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby

      - run: bundle exec rake
        working-directory: ruby
