
name: test-java

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - run: mvn install
        working-directory: java
      - run: mvn test
        working-directory: java
      - run: ./scripts/check-jar.sh
        working-directory: java
