name: test-ruby

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  build-javascript:
    uses: cucumber/html-formatter/.github/workflows/build-javascript.yml@github-ci

  test-ruby:
    needs: [build-javascript]

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby: ['2.5', '2.6', '2.7', '3.0']
        include:
          - os: windows-latest
            ruby: '3.0'
          - os: macos-latest
            ruby: '3.0'

    steps:
    - uses: actions/checkout@v2

    - name: Download javascript build artifacts
      uses: actions/download-artifact@v2
      with:
        name: javascript-dist
        path: javascript/dist

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: javascript/dist

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: ruby

    - run: bundle exec rspec
      working-directory: ruby
